version: '3'

services:
  phpapp:
    build: 
      context: ./
      dockerfile: Dockerfile
    image: phpapp:123
    ports:
      - "8080:80"
    volumes:
      - "./:/var/www/html"
    container_name: my-php-app

  db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_USERNAME: ROOT
      MYSQL_ROOT_PASSWORD: root
    container_name: myphpapp-db
      
