
name: CI

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build: 
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - uses: hadolint/hadolint-action@v2.1.0
        with:
          dockerfile: Dockerfile
      
